INSERT INTO materi (id, kode, nama) VALUES ('jfu-001', 'JFU-001', 'Java Fundamental 1')
INSERT INTO materi (id, kode, nama) VALUES ('jfu-002', 'JFU-002', 'Java Fundamental 2')
INSERT INTO materi (id, kode, nama) VALUES ('jsi-001', 'JSI-001', 'Spring Framework 1')
INSERT INTO materi (id, kode, nama) VALUES ('jsi-002', 'JSI-002', 'Spring Framework 2')
INSERT INTO materi (id, kode, nama) VALUES ('jsi-003', 'JSI-003', 'Spring Framework 3')
INSERT INTO materi (id, kode, nama) VALUES ('jjs-001', 'JJS-001', 'Angular JS 1')
INSERT INTO materi (id, kode, nama) VALUES ('jjs-002', 'JJS-002', 'Angular JS 2')